select	coalesce(pa11.ID_ANO, pa12.ID_ANO)  ID_ANO,
coalesce(pa11.ID_ORGAO_MAXI, pa12.ID_ORGAO_MAXI)  ID_ORGAO_MAXI,
max(a113.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
max(a113.NO_ORGAO_MAXI)  NO_ORGAO_MAXI,
coalesce(pa11.ID_ESFERA_ORCAMENTARIA, pa12.ID_ESFERA_ORCAMENTARIA)  ID_ESFERA_ORCAMENTARIA,
max(a16.NO_ESFERA_ORCAMENTARIA)  NO_ESFERA_ORCAMENTARIA,
coalesce(pa11.ID_UO, pa12.ID_UO)  ID_UO,
max(a114.CO_UO)  CO_UO,
max(a114.NO_UO)  NO_UO,
a14.ID_FUNCAO_PT  ID_FUNCAO_PT,
max(a116.NO_FUNCAO_PT)  ID_FUNCAO_PT0,
a14.ID_SUBFUNCAO_PT  ID_SUBFUNCAO_PT,
max(a119.NO_SUBFUNCAO_PT)  NO_SUBFUNCAO_PT,
a14.ID_PROGRAMA_PT  ID_PROGRAMA_PT,
max(a118.NO_PROGRAMA_PT)  NO_PROGRAMA_PT,
a13.ID_ACAO_PT  ID_ACAO_PT,
max(a115.NO_ACAO_PT)  NO_ACAO_PT,
coalesce(pa11.ID_UO0, pa12.ID_UO0)  ID_UO0,
coalesce(pa11.ID_FUNCAO_PT, pa12.ID_FUNCAO_PT)  ID_FUNCAO_PT1,
coalesce(pa11.ID_SUBFUNCAO_PT, pa12.ID_SUBFUNCAO_PT)  ID_SUBFUNCAO_PT0,
coalesce(pa11.ID_PROGRAMA_PT, pa12.ID_PROGRAMA_PT)  ID_PROGRAMA_PT0,
coalesce(pa11.ID_ACAO_PT, pa12.ID_ACAO_PT)  ID_ACAO_PT0,
coalesce(pa11.ID_PO, pa12.ID_PO)  ID_PO,
max(a14.NO_PO)  NO_PO,
coalesce(pa11.ID_ACAO_PT0, pa12.ID_ACAO_PT0)  ID_ACAO_PT1,
coalesce(pa11.ID_LOCALIZADOR_GASTO_PT, pa12.ID_LOCALIZADOR_GASTO_PT)  ID_LOCALIZADOR_GASTO_PT,
max(a13.CO_LOCALIZADOR_GASTO_COMP_PT)  CO_LOCALIZADOR_GASTO_COMP_PT,
max(a13.NO_LOCALIZADOR_GASTO_PT)  NO_LOCALIZADOR_GASTO_PT,
coalesce(pa11.ID_IDOC, pa12.ID_IDOC)  ID_IDOC,
max(a17.CO_IDOC)  CO_IDOC,
max(a17.NO_IDOC)  NO_IDOC,
coalesce(pa11.ID_IDUSO, pa12.ID_IDUSO)  ID_IDUSO,
max(a18.NO_IDUSO)  NO_IDUSO,
coalesce(pa11.ID_CATEGORIA_ECONOMICA_NADE, pa12.ID_CATEGORIA_ECONOMICA_NADE)  ID_CATEGORIA_ECONOMICA_NADE,
coalesce(pa11.ID_GRUPO_DESPESA_NADE, pa12.ID_GRUPO_DESPESA_NADE)  ID_GRUPO_DESPESA_NADE,
coalesce(pa11.ID_MOAP_NADE, pa12.ID_MOAP_NADE)  ID_MOAP_NADE,
coalesce(pa11.ID_ELEMENTO_DESPESA_NADE, pa12.ID_ELEMENTO_DESPESA_NADE)  ID_ELEMENTO_DESPESA_NADE,
coalesce(pa11.ID_SUBITEM_NADE, pa12.ID_SUBITEM_NADE)  ID_SUBITEM_NADE,
max(a15.CO_NATUREZA_DESPESA_DETA)  CO_NATUREZA_DESPESA_DETA,
max(a15.NO_NATUREZA_DESPESA_DETA)  NO_NATUREZA_DESPESA_DETA,
a15.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE0,
max(a117.NO_GRUPO_DESPESA_NADE)  NO_GRUPO_DESPESA_NADE,
coalesce(pa11.CO_FONTE_SOF, pa12.CO_FONTE_SOF)  CO_FONTE_SOF,
coalesce(pa11.ID_IN_RESULTADO_EOF, pa12.ID_IN_RESULTADO_EOF)  ID_IN_RESULTADO_EOF,
max(a110.NO_IN_RESULTADO_EOF)  NO_IN_RESULTADO_EOF,
coalesce(pa11.ID_IN_RESULTADO_LEI_CEOR, pa12.ID_IN_RESULTADO_LEI_CEOR)  ID_IN_RESULTADO_LEI_CEOR,
max(a111.NO_IN_RESULTADO_LEI_CEOR)  NO_IN_RESULTADO_LEI_CEOR,
coalesce(pa11.ID_IN_TP_CREDITO_CEOR, pa12.ID_IN_TP_CREDITO_CEOR)  ID_IN_TP_CREDITO_CEOR,
max(a112.NO_IN_TP_CREDITO_CEOR)  NO_IN_TP_CREDITO_CEOR,
coalesce(pa11.SN_EXCECAO_DECRETO, pa12.SN_EXCECAO_DECRETO)  SN_EXCECAO_DECRETO,
coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO)  ID_ITEM_INFORMACAO,
max(a19.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
max(a19.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
max(pa11.SALDOANTRITEMINFORMAO)  SALDOANTRITEMINFORMAO,
max(pa12.SALDORITEMINFORMAO)  SALDORITEMINFORMAO
from	(select	a18.ID_UO  ID_UO,
      a110.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
      a16.ID_IN_TP_CREDITO_CEOR  ID_IN_TP_CREDITO_CEOR,
      a16.ID_IN_RESULTADO_LEI_CEOR  ID_IN_RESULTADO_LEI_CEOR,
      a16.ID_IN_RESULTADO_EOF  ID_IN_RESULTADO_EOF,
      a11.ID_UO  ID_UO0,
      a11.ID_FUNCAO_PT  ID_FUNCAO_PT,
      a11.ID_SUBFUNCAO_PT  ID_SUBFUNCAO_PT,
      a11.ID_PROGRAMA_PT  ID_PROGRAMA_PT,
      a11.ID_ACAO_PT  ID_ACAO_PT,
      a11.ID_PO  ID_PO,
      a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
      a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
      a11.ID_MOAP_NADE  ID_MOAP_NADE,
      a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
      a11.ID_SUBITEM_NADE  ID_SUBITEM_NADE,
      a11.ID_ACAO_PT  ID_ACAO_PT0,
      a11.ID_LOCALIZADOR_GASTO_PT  ID_LOCALIZADOR_GASTO_PT,
      a14.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
      a17.ID_IDUSO  ID_IDUSO,
      a11.ID_IDOC  ID_IDOC,
      a17.CO_FONTE_SOF  CO_FONTE_SOF,
      a16.SN_EXCECAO_DECRETO  SN_EXCECAO_DECRETO,
      a11.ID_ESFERA_ORCAMENTARIA  ID_ESFERA_ORCAMENTARIA,
      a11.ID_ANO_LANC  ID_ANO,
      sum(((a11.VA_MOVIMENTO_LIQUIDO * a14.IN_OPERACAO_EXPRESSAO) * a13.PE_TAXA_ANTERIOR))  SALDOANTRITEMINFORMAO
      from	WF_LANCAMENTO_EP01	a11
      join	WD_MOEDA	a12
      on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
      join	WD_TAXA_CAMBIO_MENSAL	a13
      on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
      join	WD_ITEM_DECODIFICADO_CCON	a14
      on 	(a11.ID_ANO_LANC = a14.ID_ANO_ITEM_CONTA and 
           a11.ID_CONTA_CONTABIL_LANC = a14.ID_CONTA_CONTABIL)
      join	WA_MES_ACUM_SEM_ANO	a15
      on 	(a11.ID_MES_LANC = (a15.ID_MES_ACUM_ANO_SALDO - 1))
      join	WD_CELULA_ORCAMENTARIA	a16
      on 	(a11.ID_ANO_LANC = a16.ID_ANO_CEOR and 
           a11.ID_CELULA_ORCAMENTARIA_SK = a16.ID_CELULA_ORCAMENTARIA_SK)
      join	WD_FONTE_RECURSO_DETA	a17
      on 	(a11.ID_FONTE_RECURSO_DETA = a17.ID_FONTE_RECURSO_DETA)
      join	WD_UO_EXERCICIO	a18
      on 	(a11.ID_ANO_LANC = a18.ID_ANO and 
           a11.ID_UO = a18.ID_UO)
      join	WD_ORGAO_EXERCICIO	a19
      on 	(a18.ID_ANO = a19.ID_ANO and 
           a18.ID_ORGAO_UO = a19.ID_ORGAO)
      join	WD_ORGAO_SUPE_EXERCICIO	a110
      on 	(a19.ID_ANO = a110.ID_ANO and 
           a19.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
      where	(a14.ID_ITEM_INFORMACAO in (61, 911, 912, 604, 605, 852, 141, 122, 303, 187, 83, 421)
             and a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
             and a11.ID_ANO_LANC in (2019, 2018, 2017, 2016)
             and a13.ID_ANO = a11.ID_ANO_LANC
             and a13.ID_MES = a15.ID_MES)
      group by	a18.ID_UO,
      a110.ID_ORGAO_MAXI,
      a16.ID_IN_TP_CREDITO_CEOR,
      a16.ID_IN_RESULTADO_LEI_CEOR,
      a16.ID_IN_RESULTADO_EOF,
      a11.ID_UO,
      a11.ID_FUNCAO_PT,
      a11.ID_SUBFUNCAO_PT,
      a11.ID_PROGRAMA_PT,
      a11.ID_ACAO_PT,
      a11.ID_PO,
      a11.ID_CATEGORIA_ECONOMICA_NADE,
      a11.ID_GRUPO_DESPESA_NADE,
      a11.ID_MOAP_NADE,
      a11.ID_ELEMENTO_DESPESA_NADE,
      a11.ID_SUBITEM_NADE,
      a11.ID_ACAO_PT,
      a11.ID_LOCALIZADOR_GASTO_PT,
      a14.ID_ITEM_INFORMACAO,
      a17.ID_IDUSO,
      a11.ID_IDOC,
      a17.CO_FONTE_SOF,
      a16.SN_EXCECAO_DECRETO,
      a11.ID_ESFERA_ORCAMENTARIA,
      a11.ID_ANO_LANC
)	pa11
full outer join	(select	a18.ID_UO  ID_UO,
                 a110.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
                 a16.ID_IN_TP_CREDITO_CEOR  ID_IN_TP_CREDITO_CEOR,
                 a16.ID_IN_RESULTADO_LEI_CEOR  ID_IN_RESULTADO_LEI_CEOR,
                 a16.ID_IN_RESULTADO_EOF  ID_IN_RESULTADO_EOF,
                 a11.ID_UO  ID_UO0,
                 a11.ID_FUNCAO_PT  ID_FUNCAO_PT,
                 a11.ID_SUBFUNCAO_PT  ID_SUBFUNCAO_PT,
                 a11.ID_PROGRAMA_PT  ID_PROGRAMA_PT,
                 a11.ID_ACAO_PT  ID_ACAO_PT,
                 a11.ID_PO  ID_PO,
                 a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
                 a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
                 a11.ID_MOAP_NADE  ID_MOAP_NADE,
                 a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
                 a11.ID_SUBITEM_NADE  ID_SUBITEM_NADE,
                 a11.ID_ACAO_PT  ID_ACAO_PT0,
                 a11.ID_LOCALIZADOR_GASTO_PT  ID_LOCALIZADOR_GASTO_PT,
                 a14.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
                 a17.ID_IDUSO  ID_IDUSO,
                 a11.ID_IDOC  ID_IDOC,
                 a17.CO_FONTE_SOF  CO_FONTE_SOF,
                 a16.SN_EXCECAO_DECRETO  SN_EXCECAO_DECRETO,
                 a11.ID_ESFERA_ORCAMENTARIA  ID_ESFERA_ORCAMENTARIA,
                 a11.ID_ANO_LANC  ID_ANO,
                 sum(((a11.VA_MOVIMENTO_LIQUIDO * a14.IN_OPERACAO_EXPRESSAO) * a13.PE_TAXA))  SALDORITEMINFORMAO
                 from	WF_LANCAMENTO_EP01	a11
                 join	WD_MOEDA	a12
                 on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
                 join	WD_TAXA_CAMBIO_MENSAL	a13
                 on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
                 join	WD_ITEM_DECODIFICADO_CCON	a14
                 on 	(a11.ID_ANO_LANC = a14.ID_ANO_ITEM_CONTA and 
                      a11.ID_CONTA_CONTABIL_LANC = a14.ID_CONTA_CONTABIL)
                 join	WA_MES_ACUM_SEM_ANO	a15
                 on 	(a11.ID_MES_LANC = a15.ID_MES_ACUM_ANO_SALDO)
                 join	WD_CELULA_ORCAMENTARIA	a16
                 on 	(a11.ID_ANO_LANC = a16.ID_ANO_CEOR and 
                      a11.ID_CELULA_ORCAMENTARIA_SK = a16.ID_CELULA_ORCAMENTARIA_SK)
                 join	WD_FONTE_RECURSO_DETA	a17
                 on 	(a11.ID_FONTE_RECURSO_DETA = a17.ID_FONTE_RECURSO_DETA)
                 join	WD_UO_EXERCICIO	a18
                 on 	(a11.ID_ANO_LANC = a18.ID_ANO and 
                      a11.ID_UO = a18.ID_UO)
                 join	WD_ORGAO_EXERCICIO	a19
                 on 	(a18.ID_ANO = a19.ID_ANO and 
                      a18.ID_ORGAO_UO = a19.ID_ORGAO)
                 join	WD_ORGAO_SUPE_EXERCICIO	a110
                 on 	(a19.ID_ANO = a110.ID_ANO and 
                      a19.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
                 where	(a14.ID_ITEM_INFORMACAO in (61, 911, 912, 604, 605, 852, 141, 122, 303, 187, 83, 421)
                        and a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
                        and a11.ID_ANO_LANC in (2019, 2018, 2017, 2016)
                        and a13.ID_ANO = a11.ID_ANO_LANC
                        and a13.ID_MES = a15.ID_MES)
                 group by	a18.ID_UO,
                 a110.ID_ORGAO_MAXI,
                 a16.ID_IN_TP_CREDITO_CEOR,
                 a16.ID_IN_RESULTADO_LEI_CEOR,
                 a16.ID_IN_RESULTADO_EOF,
                 a11.ID_UO,
                 a11.ID_FUNCAO_PT,
                 a11.ID_SUBFUNCAO_PT,
                 a11.ID_PROGRAMA_PT,
                 a11.ID_ACAO_PT,
                 a11.ID_PO,
                 a11.ID_CATEGORIA_ECONOMICA_NADE,
                 a11.ID_GRUPO_DESPESA_NADE,
                 a11.ID_MOAP_NADE,
                 a11.ID_ELEMENTO_DESPESA_NADE,
                 a11.ID_SUBITEM_NADE,
                 a11.ID_ACAO_PT,
                 a11.ID_LOCALIZADOR_GASTO_PT,
                 a14.ID_ITEM_INFORMACAO,
                 a17.ID_IDUSO,
                 a11.ID_IDOC,
                 a17.CO_FONTE_SOF,
                 a16.SN_EXCECAO_DECRETO,
                 a11.ID_ESFERA_ORCAMENTARIA,
                 a11.ID_ANO_LANC
)	pa12
on 	(pa11.CO_FONTE_SOF = pa12.CO_FONTE_SOF and 
     pa11.ID_ACAO_PT = pa12.ID_ACAO_PT and 
     pa11.ID_ACAO_PT0 = pa12.ID_ACAO_PT0 and 
     pa11.ID_ANO = pa12.ID_ANO and 
     pa11.ID_CATEGORIA_ECONOMICA_NADE = pa12.ID_CATEGORIA_ECONOMICA_NADE and 
     pa11.ID_ELEMENTO_DESPESA_NADE = pa12.ID_ELEMENTO_DESPESA_NADE and 
     pa11.ID_ESFERA_ORCAMENTARIA = pa12.ID_ESFERA_ORCAMENTARIA and 
     pa11.ID_FUNCAO_PT = pa12.ID_FUNCAO_PT and 
     pa11.ID_GRUPO_DESPESA_NADE = pa12.ID_GRUPO_DESPESA_NADE and 
     pa11.ID_IDOC = pa12.ID_IDOC and 
     pa11.ID_IDUSO = pa12.ID_IDUSO and 
     pa11.ID_IN_RESULTADO_EOF = pa12.ID_IN_RESULTADO_EOF and 
     pa11.ID_IN_RESULTADO_LEI_CEOR = pa12.ID_IN_RESULTADO_LEI_CEOR and 
     pa11.ID_IN_TP_CREDITO_CEOR = pa12.ID_IN_TP_CREDITO_CEOR and 
     pa11.ID_ITEM_INFORMACAO = pa12.ID_ITEM_INFORMACAO and 
     pa11.ID_LOCALIZADOR_GASTO_PT = pa12.ID_LOCALIZADOR_GASTO_PT and 
     pa11.ID_MOAP_NADE = pa12.ID_MOAP_NADE and 
     pa11.ID_ORGAO_MAXI = pa12.ID_ORGAO_MAXI and 
     pa11.ID_PO = pa12.ID_PO and 
     pa11.ID_PROGRAMA_PT = pa12.ID_PROGRAMA_PT and 
     pa11.ID_SUBFUNCAO_PT = pa12.ID_SUBFUNCAO_PT and 
     pa11.ID_SUBITEM_NADE = pa12.ID_SUBITEM_NADE and 
     pa11.ID_UO = pa12.ID_UO and 
     pa11.ID_UO0 = pa12.ID_UO0 and 
     pa11.SN_EXCECAO_DECRETO = pa12.SN_EXCECAO_DECRETO)
join	WD_LOCALIZADOR_GASTO_PT	a13
on 	(coalesce(pa11.ID_ACAO_PT0, pa12.ID_ACAO_PT0) = a13.ID_ACAO_PT and 
     coalesce(pa11.ID_LOCALIZADOR_GASTO_PT, pa12.ID_LOCALIZADOR_GASTO_PT) = a13.ID_LOCALIZADOR_GASTO_PT)
join	WD_PO	a14
on 	(coalesce(pa11.ID_ACAO_PT, pa12.ID_ACAO_PT) = a14.ID_ACAO_PT and 
     coalesce(pa11.ID_FUNCAO_PT, pa12.ID_FUNCAO_PT) = a14.ID_FUNCAO_PT and 
     coalesce(pa11.ID_PO, pa12.ID_PO) = a14.ID_PO and 
     coalesce(pa11.ID_PROGRAMA_PT, pa12.ID_PROGRAMA_PT) = a14.ID_PROGRAMA_PT and 
     coalesce(pa11.ID_SUBFUNCAO_PT, pa12.ID_SUBFUNCAO_PT) = a14.ID_SUBFUNCAO_PT and 
     coalesce(pa11.ID_UO0, pa12.ID_UO0) = a14.ID_UO)
join	WD_NATUREZA_DESPESA_DETA	a15
on 	(coalesce(pa11.ID_CATEGORIA_ECONOMICA_NADE, pa12.ID_CATEGORIA_ECONOMICA_NADE) = a15.ID_CATEGORIA_ECONOMICA_NADE and 
     coalesce(pa11.ID_ELEMENTO_DESPESA_NADE, pa12.ID_ELEMENTO_DESPESA_NADE) = a15.ID_ELEMENTO_DESPESA_NADE and 
     coalesce(pa11.ID_GRUPO_DESPESA_NADE, pa12.ID_GRUPO_DESPESA_NADE) = a15.ID_GRUPO_DESPESA_NADE and 
     coalesce(pa11.ID_MOAP_NADE, pa12.ID_MOAP_NADE) = a15.ID_MOAP_NADE and 
     coalesce(pa11.ID_SUBITEM_NADE, pa12.ID_SUBITEM_NADE) = a15.ID_SUBITEM_NADE)
join	WD_ESFERA_ORCAMENTARIA	a16
on 	(coalesce(pa11.ID_ESFERA_ORCAMENTARIA, pa12.ID_ESFERA_ORCAMENTARIA) = a16.ID_ESFERA_ORCAMENTARIA)
join	WD_IDOC	a17
on 	(coalesce(pa11.ID_IDOC, pa12.ID_IDOC) = a17.ID_IDOC)
join	WD_IDUSO	a18
on 	(coalesce(pa11.ID_IDUSO, pa12.ID_IDUSO) = a18.ID_IDUSO)
join	WD_ITEM_INFORMACAO	a19
on 	(coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO) = a19.ID_ITEM_INFORMACAO)
join	WD_IN_RESULTADO_EOF_CEOR	a110
on 	(coalesce(pa11.ID_IN_RESULTADO_EOF, pa12.ID_IN_RESULTADO_EOF) = a110.ID_IN_RESULTADO_EOF)
join	WD_IN_RESULTADO_LEI_CEOR	a111
on 	(coalesce(pa11.ID_IN_RESULTADO_LEI_CEOR, pa12.ID_IN_RESULTADO_LEI_CEOR) = a111.ID_IN_RESULTADO_LEI_CEOR)
join	WD_IN_TP_CREDITO_CEOR	a112
on 	(coalesce(pa11.ID_IN_TP_CREDITO_CEOR, pa12.ID_IN_TP_CREDITO_CEOR) = a112.ID_IN_TP_CREDITO_CEOR)
join	WD_ORGAO_MAXI	a113
on 	(coalesce(pa11.ID_ORGAO_MAXI, pa12.ID_ORGAO_MAXI) = a113.ID_ORGAO_MAXI)
join	WD_UO	a114
on 	(coalesce(pa11.ID_UO, pa12.ID_UO) = a114.ID_UO)
join	WD_ACAO_PT	a115
on 	(a13.ID_ACAO_PT = a115.ID_ACAO_PT)
join	WD_FUNCAO_PT	a116
on 	(a14.ID_FUNCAO_PT = a116.ID_FUNCAO_PT)
join	WD_GRUPO_DESPESA_NADE	a117
on 	(a15.ID_GRUPO_DESPESA_NADE = a117.ID_GRUPO_DESPESA_NADE)
join	WD_PROGRAMA_PT	a118
on 	(a14.ID_PROGRAMA_PT = a118.ID_PROGRAMA_PT)
join	WD_SUBFUNCAO_PT	a119
on 	(a14.ID_SUBFUNCAO_PT = a119.ID_SUBFUNCAO_PT)
group by	coalesce(pa11.ID_ANO, pa12.ID_ANO),
coalesce(pa11.ID_ORGAO_MAXI, pa12.ID_ORGAO_MAXI),
coalesce(pa11.ID_ESFERA_ORCAMENTARIA, pa12.ID_ESFERA_ORCAMENTARIA),
coalesce(pa11.ID_UO, pa12.ID_UO),
a14.ID_FUNCAO_PT,
a14.ID_SUBFUNCAO_PT,
a14.ID_PROGRAMA_PT,
a13.ID_ACAO_PT,
coalesce(pa11.ID_UO0, pa12.ID_UO0),
coalesce(pa11.ID_FUNCAO_PT, pa12.ID_FUNCAO_PT),
coalesce(pa11.ID_SUBFUNCAO_PT, pa12.ID_SUBFUNCAO_PT),
coalesce(pa11.ID_PROGRAMA_PT, pa12.ID_PROGRAMA_PT),
coalesce(pa11.ID_ACAO_PT, pa12.ID_ACAO_PT),
coalesce(pa11.ID_PO, pa12.ID_PO),
coalesce(pa11.ID_ACAO_PT0, pa12.ID_ACAO_PT0),
coalesce(pa11.ID_LOCALIZADOR_GASTO_PT, pa12.ID_LOCALIZADOR_GASTO_PT),
coalesce(pa11.ID_IDOC, pa12.ID_IDOC),
coalesce(pa11.ID_IDUSO, pa12.ID_IDUSO),
coalesce(pa11.ID_CATEGORIA_ECONOMICA_NADE, pa12.ID_CATEGORIA_ECONOMICA_NADE),
coalesce(pa11.ID_GRUPO_DESPESA_NADE, pa12.ID_GRUPO_DESPESA_NADE),
coalesce(pa11.ID_MOAP_NADE, pa12.ID_MOAP_NADE),
coalesce(pa11.ID_ELEMENTO_DESPESA_NADE, pa12.ID_ELEMENTO_DESPESA_NADE),
coalesce(pa11.ID_SUBITEM_NADE, pa12.ID_SUBITEM_NADE),
a15.ID_GRUPO_DESPESA_NADE,
coalesce(pa11.CO_FONTE_SOF, pa12.CO_FONTE_SOF),
coalesce(pa11.ID_IN_RESULTADO_EOF, pa12.ID_IN_RESULTADO_EOF),
coalesce(pa11.ID_IN_RESULTADO_LEI_CEOR, pa12.ID_IN_RESULTADO_LEI_CEOR),
coalesce(pa11.ID_IN_TP_CREDITO_CEOR, pa12.ID_IN_TP_CREDITO_CEOR),
coalesce(pa11.SN_EXCECAO_DECRETO, pa12.SN_EXCECAO_DECRETO),
coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO)
